/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_AccessServiceClass_FDD_H_
#define	_AccessServiceClass_FDD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum assignedSubChannelNumber {
	assignedSubChannelNumber_b3	= 0,
	assignedSubChannelNumber_b2	= 1,
	assignedSubChannelNumber_b1	= 2,
	assignedSubChannelNumber_b0	= 3
} e_assignedSubChannelNumber;

/* AccessServiceClass-FDD */
typedef struct AccessServiceClass_FDD {
	long	 availableSignatureStartIndex;
	long	 availableSignatureEndIndex;
	BIT_STRING_t	 assignedSubChannelNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccessServiceClass_FDD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccessServiceClass_FDD;

#ifdef __cplusplus
}
#endif

#endif	/* _AccessServiceClass_FDD_H_ */
#include <asn_internal.h>
