/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_DeltaRSCP_H_
#define	_DeltaRSCP_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeltaRSCP */
typedef long	 DeltaRSCP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeltaRSCP;
asn_struct_free_f DeltaRSCP_free;
asn_struct_print_f DeltaRSCP_print;
asn_constr_check_f DeltaRSCP_constraint;
ber_type_decoder_f DeltaRSCP_decode_ber;
der_type_encoder_f DeltaRSCP_encode_der;
xer_type_decoder_f DeltaRSCP_decode_xer;
xer_type_encoder_f DeltaRSCP_encode_xer;
per_type_decoder_f DeltaRSCP_decode_uper;
per_type_encoder_f DeltaRSCP_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DeltaRSCP_H_ */
#include <asn_internal.h>
