/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_InterRATReportingQuantity_H_
#define	_InterRATReportingQuantity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ratSpecificInfo_PR {
	ratSpecificInfo_PR_NOTHING,	/* No components present */
	ratSpecificInfo_PR_gsm
} ratSpecificInfo_PR;

/* InterRATReportingQuantity */
typedef struct InterRATReportingQuantity {
	BOOLEAN_t	 utran_EstimatedQuality;
	struct ratSpecificInfo {
		ratSpecificInfo_PR present;
		union InterRATReportingQuantity__ratSpecificInfo_u {
			struct gsm {
				BOOLEAN_t	 dummy;
				BOOLEAN_t	 dummy2;
				BOOLEAN_t	 gsm_Carrier_RSSI;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} gsm;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ratSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterRATReportingQuantity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRATReportingQuantity;

#ifdef __cplusplus
}
#endif

#endif	/* _InterRATReportingQuantity_H_ */
#include <asn_internal.h>
