/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_MBMS_PreferredFrequencyInfo_r6_H_
#define	_MBMS_PreferredFrequencyInfo_r6_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "MBMS-PL-ServiceRestrictInfo-r6.h"
#include "MBMS-Qoffset.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum layerConvergenceInformation_PR {
	layerConvergenceInformation_PR_NOTHING,	/* No components present */
	layerConvergenceInformation_PR_mbms_Qoffset,
	layerConvergenceInformation_PR_mbms_HCSoffset
} layerConvergenceInformation_PR;

/* MBMS-PreferredFrequencyInfo-r6 */
typedef struct MBMS_PreferredFrequencyInfo_r6 {
	long	*mbmsPreferredFrequency	/* OPTIONAL */;
	struct layerConvergenceInformation {
		layerConvergenceInformation_PR present;
		union MBMS_PreferredFrequencyInfo_r6__layerConvergenceInformation_u {
			MBMS_Qoffset_t	 mbms_Qoffset;
			long	 mbms_HCSoffset;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} layerConvergenceInformation;
	MBMS_PL_ServiceRestrictInfo_r6_t	*mbms_PL_ServiceRestrictInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMS_PreferredFrequencyInfo_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_PreferredFrequencyInfo_r6;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMS_PreferredFrequencyInfo_r6_H_ */
#include <asn_internal.h>
