/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_Neighbour_H_
#define	_Neighbour_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NeighbourQuality.h"
#include "SFN-SFN-ObsTimeDifference2.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum modeSpecificInfo_PR {
	modeSpecificInfo_PR_NOTHING,	/* No components present */
	modeSpecificInfo_PR_fdd,
	modeSpecificInfo_PR_tdd
} modeSpecificInfo_PR;

/* Forward declarations */
struct PrimaryCPICH_Info;
struct UE_RX_TX_TimeDifferenceType2Info;
struct CellAndChannelIdentity;

/* Neighbour */
typedef struct Neighbour {
	struct modeSpecificInfo {
		modeSpecificInfo_PR present;
		union Neighbour__modeSpecificInfo_u {
			struct fdd {
				struct PrimaryCPICH_Info	*neighbourIdentity	/* OPTIONAL */;
				struct UE_RX_TX_TimeDifferenceType2Info	*uE_RX_TX_TimeDifferenceType2Info	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct tdd {
				struct CellAndChannelIdentity	*neighbourAndChannelIdentity	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	NeighbourQuality_t	 neighbourQuality;
	SFN_SFN_ObsTimeDifference2_t	 sfn_SFN_ObsTimeDifference2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Neighbour_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Neighbour;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PrimaryCPICH-Info.h"
#include "UE-RX-TX-TimeDifferenceType2Info.h"
#include "CellAndChannelIdentity.h"

#endif	/* _Neighbour_H_ */
#include <asn_internal.h>
