/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrc.asn1"
 */

#ifndef	_PhysicalSharedChannelAllocation_H_
#define	_PhysicalSharedChannelAllocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysicalSharedChannelAllocation-r3-IEs.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>
#include "DSCH-RNTI.h"
#include "RRC-TransactionIdentifier.h"
#include "PhysicalSharedChannelAllocation-r4-IEs.h"
#include "PhysicalSharedChannelAllocation-v690ext-IEs.h"
#include "PhysicalSharedChannelAllocation-v7xyext-IEs.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PhysicalSharedChannelAllocation_PR {
	PhysicalSharedChannelAllocation_PR_NOTHING,	/* No components present */
	PhysicalSharedChannelAllocation_PR_r3,
	PhysicalSharedChannelAllocation_PR_later_than_r3
} PhysicalSharedChannelAllocation_PR;
typedef enum criticalExtensions_PR {
	criticalExtensions_PR_NOTHING,	/* No components present */
	criticalExtensions_PR_r4,
	criticalExtensions_PR_criticalExtensions
} criticalExtensions_PR;

/* PhysicalSharedChannelAllocation */
typedef struct PhysicalSharedChannelAllocation {
	PhysicalSharedChannelAllocation_PR present;
	union PhysicalSharedChannelAllocation_u {
		struct r3 {
			PhysicalSharedChannelAllocation_r3_IEs_t	 physicalSharedChannelAllocation_r3;
			struct laterNonCriticalExtensions {
				BIT_STRING_t	*physicalSharedChannelAllocation_r3_add_ext	/* OPTIONAL */;
				struct nonCriticalExtensions {
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *nonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *laterNonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct later_than_r3 {
			DSCH_RNTI_t	*dsch_RNTI	/* OPTIONAL */;
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct criticalExtensions {
				criticalExtensions_PR present;
				union PhysicalSharedChannelAllocation__later_than_r3__criticalExtensions_u {
					struct r4 {
						PhysicalSharedChannelAllocation_r4_IEs_t	 physicalSharedChannelAllocation_r4;
						struct v4d0NonCriticalExtensions {
							BIT_STRING_t	*physicalSharedChannelAllocation_r4_add_ext	/* OPTIONAL */;
							struct v690NonCriticalExtensions {
								PhysicalSharedChannelAllocation_v690ext_IEs_t	 physicalSharedChannelAllocation_v690ext;
								struct v7xyNonCriticalExtensions {
									PhysicalSharedChannelAllocation_v7xyext_IEs_t	 physicalSharedChannelAllocation_v7xyext;
									struct nonCriticalExtensions {
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *nonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v7xyNonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v690NonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v4d0NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} r4;
					struct criticalExtensions {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} criticalExtensions;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhysicalSharedChannelAllocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalSharedChannelAllocation;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysicalSharedChannelAllocation_H_ */
#include <asn_internal.h>
