/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_PredefinedConfigIdentityAndValueTag_H_
#define	_PredefinedConfigIdentityAndValueTag_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PredefinedConfigIdentity.h"
#include "PredefinedConfigValueTag.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PredefinedConfigIdentityAndValueTag */
typedef struct PredefinedConfigIdentityAndValueTag {
	PredefinedConfigIdentity_t	 predefinedConfigIdentity;
	PredefinedConfigValueTag_t	 predefinedConfigValueTag;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PredefinedConfigIdentityAndValueTag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PredefinedConfigIdentityAndValueTag;

#ifdef __cplusplus
}
#endif

#endif	/* _PredefinedConfigIdentityAndValueTag_H_ */
#include <asn_internal.h>
