/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_RFC2507_Info_H_
#define	_RFC2507_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "ExpectReordering.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RFC2507-Info */
typedef struct RFC2507_Info {
	long	*f_MAX_PERIOD	/* DEFAULT 256 */;
	long	*f_MAX_TIME	/* DEFAULT 5 */;
	long	*max_HEADER	/* DEFAULT 168 */;
	long	*tcp_SPACE	/* DEFAULT 15 */;
	long	*non_TCP_SPACE	/* DEFAULT 15 */;
	ExpectReordering_t	 expectReordering;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RFC2507_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RFC2507_Info;

#ifdef __cplusplus
}
#endif

#endif	/* _RFC2507_Info_H_ */
#include <asn_internal.h>
