/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrc.asn1"
 */

#ifndef	_RRCConnectionRequest_v690ext_IEs_H_
#define	_RRCConnectionRequest_v690ext_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NULL.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ueCapabilityIndication {
	ueCapabilityIndication_hsdch	= 0,
	ueCapabilityIndication_hsdch_edch	= 1
} e_ueCapabilityIndication;
typedef enum domainIndicator_PR {
	domainIndicator_PR_NOTHING,	/* No components present */
	domainIndicator_PR_cs_domain,
	domainIndicator_PR_ps_domain
} domainIndicator_PR;
typedef enum csCallType {
	csCallType_speech	= 0,
	csCallType_video	= 1,
	csCallType_other	= 2,
	csCallType_spare	= 3
} e_csCallType;

/* Forward declarations */
struct MeasuredResultsOnRACHinterFreq;

/* RRCConnectionRequest-v690ext-IEs */
typedef struct RRCConnectionRequest_v690ext_IEs {
	long	*ueCapabilityIndication	/* OPTIONAL */;
	struct MeasuredResultsOnRACHinterFreq	*measuredResultsOnRACHinterFreq	/* OPTIONAL */;
	struct domainIndicator {
		domainIndicator_PR present;
		union RRCConnectionRequest_v690ext_IEs__domainIndicator_u {
			struct cs_domain {
				long	 csCallType;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} cs_domain;
			NULL_t	 ps_domain;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} domainIndicator;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRequest_v690ext_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ueCapabilityIndication_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_csCallType_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRequest_v690ext_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasuredResultsOnRACHinterFreq.h"

#endif	/* _RRCConnectionRequest_v690ext_IEs_H_ */
#include <asn_internal.h>
