/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_SysInfoType5_v690ext_IEs_H_
#define	_SysInfoType5_v690ext_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "CBS-DRX-Level1Information-extension-r6.h"
#include "MBMS-MCCH-ConfigurationInfo-r6.h"
#include "SCCPCH-SystemInformation-MBMS-r6.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum edch_CellIndicator {
	edch_CellIndicator_edch_CapableCell	= 0
} e_edch_CellIndicator;
typedef enum sccpch_SystemInformation_MBMS_PR {
	sccpch_SystemInformation_MBMS_PR_NOTHING,	/* No components present */
	sccpch_SystemInformation_MBMS_PR_mcchOnSCCPCHusedForNonMBMS,
	sccpch_SystemInformation_MBMS_PR_mcchOnSCCPCHusedOnlyForMBMS
} sccpch_SystemInformation_MBMS_PR;

/* Forward declarations */
struct AdditionalPRACH_TF_and_TFCS_CCCH_List;

/* SysInfoType5-v690ext-IEs */
typedef struct SysInfoType5_v690ext_IEs {
	long	*edch_CellIndicator	/* OPTIONAL */;
	struct sccpch_SystemInformation_MBMS {
		sccpch_SystemInformation_MBMS_PR present;
		union SysInfoType5_v690ext_IEs__sccpch_SystemInformation_MBMS_u {
			MBMS_MCCH_ConfigurationInfo_r6_t	 mcchOnSCCPCHusedForNonMBMS;
			SCCPCH_SystemInformation_MBMS_r6_t	 mcchOnSCCPCHusedOnlyForMBMS;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sccpch_SystemInformation_MBMS;
	struct AdditionalPRACH_TF_and_TFCS_CCCH_List	*additionalPRACH_TF_and_TFCS_CCCH_List	/* OPTIONAL */;
	CBS_DRX_Level1Information_extension_r6_t	*cBS_DRX_Level1Information_extension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType5_v690ext_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_edch_CellIndicator_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType5_v690ext_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AdditionalPRACH-TF-and-TFCS-CCCH-List.h"

#endif	/* _SysInfoType5_v690ext_IEs_H_ */
#include <asn_internal.h>
