/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_UE_RadioAccessCapabilityComp2_H_
#define	_UE_RadioAccessCapabilityComp2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DL-CapabilityWithSimultaneousHS-DSCHConfig.h"
#include "HSDSCH-physical-layer-category.h"
#include "PhysicalChannelCapability-edch-r6.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UE-RadioAccessCapabilityComp2 */
typedef struct UE_RadioAccessCapabilityComp2 {
	struct fddPhysicalChannelCapab_hspdsch_edch {
		DL_CapabilityWithSimultaneousHS_DSCHConfig_t	*dl_CapabilityWithSimultaneousHS_DSCHConfig	/* OPTIONAL */;
		HSDSCH_physical_layer_category_t	 physicalChannelCapabComp_hspdsch_r6;
		PhysicalChannelCapability_edch_r6_t	 physicalChannelCapability_edch_r6;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *fddPhysicalChannelCapab_hspdsch_edch;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_RadioAccessCapabilityComp2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_RadioAccessCapabilityComp2;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_RadioAccessCapabilityComp2_H_ */
#include <asn_internal.h>
