/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_UL_DPCH_Info_r7_H_
#define	_UL_DPCH_Info_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ScramblingCodeType.h"
#include "UL-ScramblingCode.h"
#include "NumberOfDPDCH.h"
#include "SpreadingFactor.h"
#include <BOOLEAN.h>
#include "NumberOfFBI-Bits.h"
#include "PuncturingLimit.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum modeSpecificInfo_PR {
	modeSpecificInfo_PR_NOTHING,	/* No components present */
	modeSpecificInfo_PR_fdd,
	modeSpecificInfo_PR_tdd
} modeSpecificInfo_PR;
typedef enum dpdchPresence_PR {
	dpdchPresence_PR_NOTHING,	/* No components present */
	dpdchPresence_PR_present,
	dpdchPresence_PR_notPresent
} dpdchPresence_PR;

/* Forward declarations */
struct UL_DPCH_PowerControlInfo_r6;
struct UL_TimingAdvanceControl_r7;
struct UL_CCTrCHList_r7;
struct UL_CCTrCHListToRemove;

/* UL-DPCH-Info-r7 */
typedef struct UL_DPCH_Info_r7 {
	struct UL_DPCH_PowerControlInfo_r6	*ul_DPCH_PowerControlInfo	/* OPTIONAL */;
	struct modeSpecificInfo {
		modeSpecificInfo_PR present;
		union UL_DPCH_Info_r7__modeSpecificInfo_u {
			struct fdd {
				ScramblingCodeType_t	 scramblingCodeType;
				UL_ScramblingCode_t	 scramblingCode;
				struct dpdchPresence {
					dpdchPresence_PR present;
					union UL_DPCH_Info_r7__modeSpecificInfo__fdd__dpdchPresence_u {
						struct present {
							NumberOfDPDCH_t	*numberOfDPDCH	/* DEFAULT 1 */;
							SpreadingFactor_t	 spreadingFactor;
							BOOLEAN_t	 tfci_Existence;
							NumberOfFBI_Bits_t	*numberOfFBI_Bits	/* OPTIONAL */;
							PuncturingLimit_t	 puncturingLimit;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} present;
						struct notPresent {
							BOOLEAN_t	 tfci_Existence;
							NumberOfFBI_Bits_t	*numberOfFBI_Bits	/* OPTIONAL */;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} notPresent;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} dpdchPresence;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct tdd {
				struct UL_TimingAdvanceControl_r7	*ul_TimingAdvance	/* OPTIONAL */;
				struct UL_CCTrCHList_r7	*ul_CCTrCHList	/* OPTIONAL */;
				struct UL_CCTrCHListToRemove	*ul_CCTrCHListToRemove	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_DPCH_Info_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_DPCH_Info_r7;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UL-DPCH-PowerControlInfo-r6.h"
#include "UL-TimingAdvanceControl-r7.h"
#include "UL-CCTrCHList-r7.h"
#include "UL-CCTrCHListToRemove.h"

#endif	/* _UL_DPCH_Info_r7_H_ */
#include <asn_internal.h>
