/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_Wi_LCR_H_
#define	_Wi_LCR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Wi-LCR */
typedef long	 Wi_LCR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Wi_LCR;
asn_struct_free_f Wi_LCR_free;
asn_struct_print_f Wi_LCR_print;
asn_constr_check_f Wi_LCR_constraint;
ber_type_decoder_f Wi_LCR_decode_ber;
der_type_encoder_f Wi_LCR_encode_der;
xer_type_decoder_f Wi_LCR_decode_xer;
xer_type_encoder_f Wi_LCR_encode_xer;
per_type_decoder_f Wi_LCR_decode_uper;
per_type_encoder_f Wi_LCR_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Wi_LCR_H_ */
#include <asn_internal.h>
