/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_DL_CommonInformation_r4_H_
#define	_DL_CommonInformation_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DefaultDPCH-OffsetValueFDD.h"
#include "TX-DiversityMode.h"
#include <constr_SEQUENCE.h>
#include "DefaultDPCH-OffsetValueTDD.h"
#include <NULL.h>
#include <BOOLEAN.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum modeSpecificInfo_PR {
	modeSpecificInfo_PR_NOTHING,	/* No components present */
	modeSpecificInfo_PR_fdd,
	modeSpecificInfo_PR_tdd
} modeSpecificInfo_PR;
typedef enum tddOption_PR {
	tddOption_PR_NOTHING,	/* No components present */
	tddOption_PR_tdd384,
	tddOption_PR_tdd128
} tddOption_PR;

/* Forward declarations */
struct DL_DPCH_InfoCommon_r4;
struct DPCH_CompressedModeInfo;
struct SSDT_Information_r4;

/* DL-CommonInformation-r4 */
typedef struct DL_CommonInformation_r4 {
	struct DL_DPCH_InfoCommon_r4	*dl_DPCH_InfoCommon	/* OPTIONAL */;
	struct modeSpecificInfo {
		modeSpecificInfo_PR present;
		union DL_CommonInformation_r4__modeSpecificInfo_u {
			struct fdd {
				DefaultDPCH_OffsetValueFDD_t	*defaultDPCH_OffsetValue	/* OPTIONAL */;
				struct DPCH_CompressedModeInfo	*dpch_CompressedModeInfo	/* OPTIONAL */;
				TX_DiversityMode_t	*tx_DiversityMode	/* OPTIONAL */;
				struct SSDT_Information_r4	*dummy	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct tdd {
				struct tddOption {
					tddOption_PR present;
					union DL_CommonInformation_r4__modeSpecificInfo__tdd__tddOption_u {
						NULL_t	 tdd384;
						struct tdd128 {
							BOOLEAN_t	 tstd_Indicator;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} tdd128;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} tddOption;
				DefaultDPCH_OffsetValueTDD_t	*defaultDPCH_OffsetValue	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_CommonInformation_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_CommonInformation_r4;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DL-DPCH-InfoCommon-r4.h"
#include "DPCH-CompressedModeInfo.h"
#include "SSDT-Information-r4.h"

#endif	/* _DL_CommonInformation_r4_H_ */
#include <asn_internal.h>
