/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "rrc.asn1"
 */

#ifndef	_DL_PhysChCapabilityFDD_r5_H_
#define	_DL_PhysChCapabilityFDD_r5_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "MaxNoPhysChBitsReceived.h"
#include <BOOLEAN.h>
#include "SimultaneousSCCPCH-DPCH-Reception.h"
#include "SupportOfDedicatedPilotsForChEstimation.h"
#include <NULL.h>
#include "HSDSCH-physical-layer-category.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum fdd_hspdsch_PR {
	fdd_hspdsch_PR_NOTHING,	/* No components present */
	fdd_hspdsch_PR_supported,
	fdd_hspdsch_PR_unsupported
} fdd_hspdsch_PR;

/* DL-PhysChCapabilityFDD-r5 */
typedef struct DL_PhysChCapabilityFDD_r5 {
	long	 maxNoDPCH_PDSCH_Codes;
	MaxNoPhysChBitsReceived_t	 maxNoPhysChBitsReceived;
	BOOLEAN_t	 supportForSF_512;
	BOOLEAN_t	 dummy;
	SimultaneousSCCPCH_DPCH_Reception_t	 dummy2;
	SupportOfDedicatedPilotsForChEstimation_t	*dummy3	/* OPTIONAL */;
	struct fdd_hspdsch {
		fdd_hspdsch_PR present;
		union DL_PhysChCapabilityFDD_r5__fdd_hspdsch_u {
			struct supported {
				HSDSCH_physical_layer_category_t	 hsdsch_physical_layer_category;
				BOOLEAN_t	 dummy;
				BOOLEAN_t	 dummy2;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} supported;
			NULL_t	 unsupported;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} fdd_hspdsch;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_PhysChCapabilityFDD_r5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_PhysChCapabilityFDD_r5;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_PhysChCapabilityFDD_r5_H_ */
#include <asn_internal.h>
