/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#include "DL-PhysChCapabilityTDD-768.h"

static asn_TYPE_member_t asn_MBR_DL_PhysChCapabilityTDD_768_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DL_PhysChCapabilityTDD_768, maxTS_PerFrame),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MaxTS_PerFrame,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"maxTS-PerFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_PhysChCapabilityTDD_768, maxPhysChPerFrame),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MaxPhysChPerFrame_768,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"maxPhysChPerFrame"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_PhysChCapabilityTDD_768, minimumSF),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MinimumSF_DL_768,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"minimumSF"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_PhysChCapabilityTDD_768, supportOfPDSCH),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"supportOfPDSCH"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DL_PhysChCapabilityTDD_768, maxPhysChPerTS),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MaxPhysChPerTS_768,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"maxPhysChPerTS"
		},
};
static const ber_tlv_tag_t asn_DEF_DL_PhysChCapabilityTDD_768_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DL_PhysChCapabilityTDD_768_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maxTS-PerFrame */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* maxPhysChPerFrame */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* minimumSF */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* supportOfPDSCH */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* maxPhysChPerTS */
};
static asn_SEQUENCE_specifics_t asn_SPC_DL_PhysChCapabilityTDD_768_specs_1 = {
	sizeof(struct DL_PhysChCapabilityTDD_768),
	offsetof(struct DL_PhysChCapabilityTDD_768, _asn_ctx),
	asn_MAP_DL_PhysChCapabilityTDD_768_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DL_PhysChCapabilityTDD_768 = {
	"DL-PhysChCapabilityTDD-768",
	"DL-PhysChCapabilityTDD-768",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DL_PhysChCapabilityTDD_768_tags_1,
	sizeof(asn_DEF_DL_PhysChCapabilityTDD_768_tags_1)
		/sizeof(asn_DEF_DL_PhysChCapabilityTDD_768_tags_1[0]), /* 1 */
	asn_DEF_DL_PhysChCapabilityTDD_768_tags_1,	/* Same as above */
	sizeof(asn_DEF_DL_PhysChCapabilityTDD_768_tags_1)
		/sizeof(asn_DEF_DL_PhysChCapabilityTDD_768_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DL_PhysChCapabilityTDD_768_1,
	5,	/* Elements count */
	&asn_SPC_DL_PhysChCapabilityTDD_768_specs_1	/* Additional specs */
};

