/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrc.asn1"
 */

#ifndef	_DownlinkDirectTransfer_H_
#define	_DownlinkDirectTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DownlinkDirectTransfer-r3-IEs.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>
#include "RRC-TransactionIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DownlinkDirectTransfer_PR {
	DownlinkDirectTransfer_PR_NOTHING,	/* No components present */
	DownlinkDirectTransfer_PR_r3,
	DownlinkDirectTransfer_PR_later_than_r3
} DownlinkDirectTransfer_PR;

/* DownlinkDirectTransfer */
typedef struct DownlinkDirectTransfer {
	DownlinkDirectTransfer_PR present;
	union DownlinkDirectTransfer_u {
		struct r3 {
			DownlinkDirectTransfer_r3_IEs_t	 downlinkDirectTransfer_r3;
			struct laterNonCriticalExtensions {
				BIT_STRING_t	*downlinkDirectTransfer_r3_add_ext	/* OPTIONAL */;
				struct nonCriticalExtensions {
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *nonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *laterNonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct later_than_r3 {
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct criticalExtensions {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DownlinkDirectTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DownlinkDirectTransfer;

#ifdef __cplusplus
}
#endif

#endif	/* _DownlinkDirectTransfer_H_ */
#include <asn_internal.h>
