/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_EXT_UL_TimingAdvance_H_
#define	_EXT_UL_TimingAdvance_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum modeSpecificInfo_PR {
	modeSpecificInfo_PR_NOTHING,	/* No components present */
	modeSpecificInfo_PR_tdd384,
	modeSpecificInfo_PR_tdd768
} modeSpecificInfo_PR;

/* EXT-UL-TimingAdvance */
typedef struct EXT_UL_TimingAdvance {
	struct modeSpecificInfo {
		modeSpecificInfo_PR present;
		union EXT_UL_TimingAdvance__modeSpecificInfo_u {
			struct tdd384 {
				long	 ex_ul_TimingAdvance;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd384;
			struct tdd768 {
				long	 ex_ul_TimingAdvance;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd768;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EXT_UL_TimingAdvance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EXT_UL_TimingAdvance;

#ifdef __cplusplus
}
#endif

#endif	/* _EXT_UL_TimingAdvance_H_ */
#include <asn_internal.h>
