/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrc.asn1"
 */

#ifndef	_HandoverFromUTRANCommand_GSM_H_
#define	_HandoverFromUTRANCommand_GSM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HandoverFromUTRANCommand-GSM-r3-IEs.h"
#include <BIT_STRING.h>
#include "HandoverFromUTRANCommand-GSM-v690ext-IEs.h"
#include <constr_SEQUENCE.h>
#include "RRC-TransactionIdentifier.h"
#include "HandoverFromUTRANCommand-GSM-r6-IEs.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HandoverFromUTRANCommand_GSM_PR {
	HandoverFromUTRANCommand_GSM_PR_NOTHING,	/* No components present */
	HandoverFromUTRANCommand_GSM_PR_r3,
	HandoverFromUTRANCommand_GSM_PR_later_than_r3
} HandoverFromUTRANCommand_GSM_PR;
typedef enum criticalExtensions_PR {
	criticalExtensions_PR_NOTHING,	/* No components present */
	criticalExtensions_PR_r6,
	criticalExtensions_PR_criticalExtensions
} criticalExtensions_PR;

/* HandoverFromUTRANCommand-GSM */
typedef struct HandoverFromUTRANCommand_GSM {
	HandoverFromUTRANCommand_GSM_PR present;
	union HandoverFromUTRANCommand_GSM_u {
		struct r3 {
			HandoverFromUTRANCommand_GSM_r3_IEs_t	 handoverFromUTRANCommand_GSM_r3;
			struct laterNonCriticalExtensions {
				BIT_STRING_t	*handoverFromUTRANCommand_GSM_r3_add_ext	/* OPTIONAL */;
				struct v690NonCriticalExtensions {
					HandoverFromUTRANCommand_GSM_v690ext_IEs_t	 handoverFromUTRANCommand_GSM_v690ext;
					struct nonCriticalExtensions {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *nonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *v690NonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *laterNonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct later_than_r3 {
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct criticalExtensions {
				criticalExtensions_PR present;
				union HandoverFromUTRANCommand_GSM__later_than_r3__criticalExtensions_u {
					struct r6 {
						HandoverFromUTRANCommand_GSM_r6_IEs_t	 handoverFromUTRANCommand_GSM_r6;
						BIT_STRING_t	*handoverFromUTRANCommand_GSM_r6_add_ext	/* OPTIONAL */;
						struct nonCriticalExtensions {
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *nonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} r6;
					struct criticalExtensions {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} criticalExtensions;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverFromUTRANCommand_GSM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverFromUTRANCommand_GSM;

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverFromUTRANCommand_GSM_H_ */
#include <asn_internal.h>
