/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_IndividualDL_CCTrCH_Info_H_
#define	_IndividualDL_CCTrCH_Info_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TFCS-Identity.h"
#include "TFCS.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum tfcs_SignallingMode_PR {
	tfcs_SignallingMode_PR_NOTHING,	/* No components present */
	tfcs_SignallingMode_PR_explicit_config,
	tfcs_SignallingMode_PR_sameAsUL
} tfcs_SignallingMode_PR;

/* IndividualDL-CCTrCH-Info */
typedef struct IndividualDL_CCTrCH_Info {
	TFCS_Identity_t	 dl_TFCS_Identity;
	struct tfcs_SignallingMode {
		tfcs_SignallingMode_PR present;
		union IndividualDL_CCTrCH_Info__tfcs_SignallingMode_u {
			TFCS_t	 explicit_config;
			TFCS_Identity_t	 sameAsUL;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tfcs_SignallingMode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IndividualDL_CCTrCH_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IndividualDL_CCTrCH_Info;

#ifdef __cplusplus
}
#endif

#endif	/* _IndividualDL_CCTrCH_Info_H_ */
#include <asn_internal.h>
