/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrc.asn1"
 */

#include "InitialDirectTransfer.h"

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_14 = {
	sizeof(struct nonCriticalExtensions),
	offsetof(struct nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_14 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_14,
	sizeof(asn_DEF_nonCriticalExtensions_tags_14)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_14[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_14,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_14)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v690NonCriticalExtensions, initialDirectTransfer_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitialDirectTransfer_v690ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initialDirectTransfer-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v690NonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_12[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initialDirectTransfer-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_12 = {
	sizeof(struct v690NonCriticalExtensions),
	offsetof(struct v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_12,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_12,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_12 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v690NonCriticalExtensions_tags_12,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_12[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_12,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v690NonCriticalExtensions_12,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v590NonCriticalExtensions_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v590NonCriticalExtensions, initialDirectTransfer_v590ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitialDirectTransfer_v590ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initialDirectTransfer-v590ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v590NonCriticalExtensions, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_v590NonCriticalExtensions_oms_10[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v590NonCriticalExtensions_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v590NonCriticalExtensions_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initialDirectTransfer-v590ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v590NonCriticalExtensions_specs_10 = {
	sizeof(struct v590NonCriticalExtensions),
	offsetof(struct v590NonCriticalExtensions, _asn_ctx),
	asn_MAP_v590NonCriticalExtensions_tag2el_10,
	2,	/* Count of tags in the map */
	asn_MAP_v590NonCriticalExtensions_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v590NonCriticalExtensions_10 = {
	"v590NonCriticalExtensions",
	"v590NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v590NonCriticalExtensions_tags_10,
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_10[0]) - 1, /* 1 */
	asn_DEF_v590NonCriticalExtensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v590NonCriticalExtensions_10,
	2,	/* Elements count */
	&asn_SPC_v590NonCriticalExtensions_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_laterNonCriticalExtensions_8[] = {
	{ ATF_POINTER, 2, offsetof(struct laterNonCriticalExtensions, initialDirectTransfer_r3_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initialDirectTransfer-r3-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct laterNonCriticalExtensions, v590NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v590NonCriticalExtensions_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v590NonCriticalExtensions"
		},
};
static const int asn_MAP_laterNonCriticalExtensions_oms_8[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_laterNonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_laterNonCriticalExtensions_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initialDirectTransfer-r3-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v590NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_laterNonCriticalExtensions_specs_8 = {
	sizeof(struct laterNonCriticalExtensions),
	offsetof(struct laterNonCriticalExtensions, _asn_ctx),
	asn_MAP_laterNonCriticalExtensions_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_laterNonCriticalExtensions_oms_8,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_laterNonCriticalExtensions_8 = {
	"laterNonCriticalExtensions",
	"laterNonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_laterNonCriticalExtensions_tags_8,
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_laterNonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_laterNonCriticalExtensions_8,
	2,	/* Elements count */
	&asn_SPC_laterNonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v3a0NonCriticalExtensions_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v3a0NonCriticalExtensions, initialDirectTransfer_v3a0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitialDirectTransfer_v3a0ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initialDirectTransfer-v3a0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v3a0NonCriticalExtensions, laterNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_laterNonCriticalExtensions_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"laterNonCriticalExtensions"
		},
};
static const int asn_MAP_v3a0NonCriticalExtensions_oms_6[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v3a0NonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v3a0NonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initialDirectTransfer-v3a0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* laterNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v3a0NonCriticalExtensions_specs_6 = {
	sizeof(struct v3a0NonCriticalExtensions),
	offsetof(struct v3a0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v3a0NonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_v3a0NonCriticalExtensions_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v3a0NonCriticalExtensions_6 = {
	"v3a0NonCriticalExtensions",
	"v3a0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v3a0NonCriticalExtensions_tags_6,
	sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_v3a0NonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v3a0NonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_v3a0NonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_InitialDirectTransfer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitialDirectTransfer, cn_DomainIdentity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CN_DomainIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cn-DomainIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialDirectTransfer, intraDomainNasNodeSelector),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntraDomainNasNodeSelector,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"intraDomainNasNodeSelector"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitialDirectTransfer, nas_Message),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NAS_Message,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nas-Message"
		},
	{ ATF_POINTER, 2, offsetof(struct InitialDirectTransfer, measuredResultsOnRACH),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasuredResultsOnRACH,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measuredResultsOnRACH"
		},
	{ ATF_POINTER, 1, offsetof(struct InitialDirectTransfer, v3a0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_v3a0NonCriticalExtensions_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v3a0NonCriticalExtensions"
		},
};
static const int asn_MAP_InitialDirectTransfer_oms_1[] = { 3, 4 };
static const ber_tlv_tag_t asn_DEF_InitialDirectTransfer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitialDirectTransfer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cn-DomainIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* intraDomainNasNodeSelector */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nas-Message */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* measuredResultsOnRACH */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* v3a0NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_InitialDirectTransfer_specs_1 = {
	sizeof(struct InitialDirectTransfer),
	offsetof(struct InitialDirectTransfer, _asn_ctx),
	asn_MAP_InitialDirectTransfer_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_InitialDirectTransfer_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_InitialDirectTransfer = {
	"InitialDirectTransfer",
	"InitialDirectTransfer",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_InitialDirectTransfer_tags_1,
	sizeof(asn_DEF_InitialDirectTransfer_tags_1)
		/sizeof(asn_DEF_InitialDirectTransfer_tags_1[0]), /* 1 */
	asn_DEF_InitialDirectTransfer_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitialDirectTransfer_tags_1)
		/sizeof(asn_DEF_InitialDirectTransfer_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_InitialDirectTransfer_1,
	5,	/* Elements count */
	&asn_SPC_InitialDirectTransfer_specs_1	/* Additional specs */
};

