/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_IntegrityProtectionModeInfo_H_
#define	_IntegrityProtectionModeInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IntegrityProtectionModeCommand.h"
#include "IntegrityProtectionAlgorithm.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntegrityProtectionModeInfo */
typedef struct IntegrityProtectionModeInfo {
	IntegrityProtectionModeCommand_t	 integrityProtectionModeCommand;
	IntegrityProtectionAlgorithm_t	*integrityProtectionAlgorithm	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntegrityProtectionModeInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntegrityProtectionModeInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _IntegrityProtectionModeInfo_H_ */
#include <asn_internal.h>
