/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#include "InterFreqMeasQuantity.h"

static asn_per_constraints_t asn_PER_type_modeSpecificInfo_constr_7 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_reportingCriteria_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_intraFreqReportingCriteria_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct intraFreqReportingCriteria, intraFreqMeasQuantity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntraFreqMeasQuantity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"intraFreqMeasQuantity"
		},
};
static const ber_tlv_tag_t asn_DEF_intraFreqReportingCriteria_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_intraFreqReportingCriteria_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* intraFreqMeasQuantity */
};
static asn_SEQUENCE_specifics_t asn_SPC_intraFreqReportingCriteria_specs_3 = {
	sizeof(struct intraFreqReportingCriteria),
	offsetof(struct intraFreqReportingCriteria, _asn_ctx),
	asn_MAP_intraFreqReportingCriteria_tag2el_3,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_intraFreqReportingCriteria_3 = {
	"intraFreqReportingCriteria",
	"intraFreqReportingCriteria",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_intraFreqReportingCriteria_tags_3,
	sizeof(asn_DEF_intraFreqReportingCriteria_tags_3)
		/sizeof(asn_DEF_intraFreqReportingCriteria_tags_3[0]) - 1, /* 1 */
	asn_DEF_intraFreqReportingCriteria_tags_3,	/* Same as above */
	sizeof(asn_DEF_intraFreqReportingCriteria_tags_3)
		/sizeof(asn_DEF_intraFreqReportingCriteria_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_intraFreqReportingCriteria_3,
	1,	/* Elements count */
	&asn_SPC_intraFreqReportingCriteria_specs_3	/* Additional specs */
};

static int asn_DFL_6_set_0(int set_value, void **sptr) {
	FilterCoefficient_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		*st = 0;
		return 0;
	} else {
		/* Test default value 0 */
		return (*st == 0);
	}
}
static asn_TYPE_member_t asn_MBR_fdd_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct fdd, freqQualityEstimateQuantity_FDD),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreqQualityEstimateQuantity_FDD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"freqQualityEstimateQuantity-FDD"
		},
};
static const ber_tlv_tag_t asn_DEF_fdd_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_fdd_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* freqQualityEstimateQuantity-FDD */
};
static asn_SEQUENCE_specifics_t asn_SPC_fdd_specs_8 = {
	sizeof(struct fdd),
	offsetof(struct fdd, _asn_ctx),
	asn_MAP_fdd_tag2el_8,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fdd_8 = {
	"fdd",
	"fdd",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_fdd_tags_8,
	sizeof(asn_DEF_fdd_tags_8)
		/sizeof(asn_DEF_fdd_tags_8[0]) - 1, /* 1 */
	asn_DEF_fdd_tags_8,	/* Same as above */
	sizeof(asn_DEF_fdd_tags_8)
		/sizeof(asn_DEF_fdd_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_fdd_8,
	1,	/* Elements count */
	&asn_SPC_fdd_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_tdd_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct tdd, freqQualityEstimateQuantity_TDD),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FreqQualityEstimateQuantity_TDD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"freqQualityEstimateQuantity-TDD"
		},
};
static const ber_tlv_tag_t asn_DEF_tdd_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_tdd_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* freqQualityEstimateQuantity-TDD */
};
static asn_SEQUENCE_specifics_t asn_SPC_tdd_specs_10 = {
	sizeof(struct tdd),
	offsetof(struct tdd, _asn_ctx),
	asn_MAP_tdd_tag2el_10,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tdd_10 = {
	"tdd",
	"tdd",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_tdd_tags_10,
	sizeof(asn_DEF_tdd_tags_10)
		/sizeof(asn_DEF_tdd_tags_10[0]) - 1, /* 1 */
	asn_DEF_tdd_tags_10,	/* Same as above */
	sizeof(asn_DEF_tdd_tags_10)
		/sizeof(asn_DEF_tdd_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_tdd_10,
	1,	/* Elements count */
	&asn_SPC_tdd_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_modeSpecificInfo_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct modeSpecificInfo, choice.fdd),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_fdd_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fdd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct modeSpecificInfo, choice.tdd),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_tdd_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tdd"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_modeSpecificInfo_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd */
};
static asn_CHOICE_specifics_t asn_SPC_modeSpecificInfo_specs_7 = {
	sizeof(struct modeSpecificInfo),
	offsetof(struct modeSpecificInfo, _asn_ctx),
	offsetof(struct modeSpecificInfo, present),
	sizeof(((struct modeSpecificInfo *)0)->present),
	asn_MAP_modeSpecificInfo_tag2el_7,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_modeSpecificInfo_7 = {
	"modeSpecificInfo",
	"modeSpecificInfo",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_modeSpecificInfo_constr_7,
	asn_MBR_modeSpecificInfo_7,
	2,	/* Elements count */
	&asn_SPC_modeSpecificInfo_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_interFreqReportingCriteria_5[] = {
	{ ATF_NOFLAGS, 1, offsetof(struct interFreqReportingCriteria, filterCoefficient),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FilterCoefficient,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		asn_DFL_6_set_0,	/* DEFAULT 0 */
		"filterCoefficient"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct interFreqReportingCriteria, modeSpecificInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_modeSpecificInfo_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"modeSpecificInfo"
		},
};
static const int asn_MAP_interFreqReportingCriteria_oms_5[] = { 0 };
static const ber_tlv_tag_t asn_DEF_interFreqReportingCriteria_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_interFreqReportingCriteria_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* filterCoefficient */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* modeSpecificInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_interFreqReportingCriteria_specs_5 = {
	sizeof(struct interFreqReportingCriteria),
	offsetof(struct interFreqReportingCriteria, _asn_ctx),
	asn_MAP_interFreqReportingCriteria_tag2el_5,
	2,	/* Count of tags in the map */
	asn_MAP_interFreqReportingCriteria_oms_5,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_interFreqReportingCriteria_5 = {
	"interFreqReportingCriteria",
	"interFreqReportingCriteria",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_interFreqReportingCriteria_tags_5,
	sizeof(asn_DEF_interFreqReportingCriteria_tags_5)
		/sizeof(asn_DEF_interFreqReportingCriteria_tags_5[0]) - 1, /* 1 */
	asn_DEF_interFreqReportingCriteria_tags_5,	/* Same as above */
	sizeof(asn_DEF_interFreqReportingCriteria_tags_5)
		/sizeof(asn_DEF_interFreqReportingCriteria_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_interFreqReportingCriteria_5,
	2,	/* Elements count */
	&asn_SPC_interFreqReportingCriteria_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_reportingCriteria_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct reportingCriteria, choice.intraFreqReportingCriteria),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_intraFreqReportingCriteria_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"intraFreqReportingCriteria"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct reportingCriteria, choice.interFreqReportingCriteria),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_interFreqReportingCriteria_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"interFreqReportingCriteria"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_reportingCriteria_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* intraFreqReportingCriteria */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* interFreqReportingCriteria */
};
static asn_CHOICE_specifics_t asn_SPC_reportingCriteria_specs_2 = {
	sizeof(struct reportingCriteria),
	offsetof(struct reportingCriteria, _asn_ctx),
	offsetof(struct reportingCriteria, present),
	sizeof(((struct reportingCriteria *)0)->present),
	asn_MAP_reportingCriteria_tag2el_2,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reportingCriteria_2 = {
	"reportingCriteria",
	"reportingCriteria",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_reportingCriteria_constr_2,
	asn_MBR_reportingCriteria_2,
	2,	/* Elements count */
	&asn_SPC_reportingCriteria_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_InterFreqMeasQuantity_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InterFreqMeasQuantity, reportingCriteria),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_reportingCriteria_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportingCriteria"
		},
};
static const ber_tlv_tag_t asn_DEF_InterFreqMeasQuantity_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InterFreqMeasQuantity_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* reportingCriteria */
};
static asn_SEQUENCE_specifics_t asn_SPC_InterFreqMeasQuantity_specs_1 = {
	sizeof(struct InterFreqMeasQuantity),
	offsetof(struct InterFreqMeasQuantity, _asn_ctx),
	asn_MAP_InterFreqMeasQuantity_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_InterFreqMeasQuantity = {
	"InterFreqMeasQuantity",
	"InterFreqMeasQuantity",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_InterFreqMeasQuantity_tags_1,
	sizeof(asn_DEF_InterFreqMeasQuantity_tags_1)
		/sizeof(asn_DEF_InterFreqMeasQuantity_tags_1[0]), /* 1 */
	asn_DEF_InterFreqMeasQuantity_tags_1,	/* Same as above */
	sizeof(asn_DEF_InterFreqMeasQuantity_tags_1)
		/sizeof(asn_DEF_InterFreqMeasQuantity_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_InterFreqMeasQuantity_1,
	1,	/* Elements count */
	&asn_SPC_InterFreqMeasQuantity_specs_1	/* Additional specs */
};

