/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrc.asn1"
 */

#ifndef	_InterRATHandoverInfo_H_
#define	_InterRATHandoverInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "PredefinedConfigStatusList.h"
#include <constr_CHOICE.h>
#include "UE-SecurityInformation.h"
#include <OCTET_STRING.h>
#include "InterRATHandoverInfo-v390ext-IEs.h"
#include "InterRATHandoverInfo-v3a0ext-IEs.h"
#include "InterRATHandoverInfo-v3d0ext-IEs.h"
#include <BIT_STRING.h>
#include "InterRATHandoverInfo-v3g0ext-IEs.h"
#include "InterRATHandoverInfo-v4b0ext-IEs.h"
#include "InterRATHandoverInfo-v4d0ext-IEs.h"
#include "InterRATHandoverInfo-v590ext-IEs.h"
#include "InterRATHandoverInfo-v690ext-IEs.h"
#include "InterRATHandoverInfo-v7xyext-IEs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum predefinedConfigStatusList_PR {
	predefinedConfigStatusList_PR_NOTHING,	/* No components present */
	predefinedConfigStatusList_PR_absent,
	predefinedConfigStatusList_PR_present
} predefinedConfigStatusList_PR;
typedef enum uE_SecurityInformation_PR {
	uE_SecurityInformation_PR_NOTHING,	/* No components present */
	uE_SecurityInformation_PR_absent,
	uE_SecurityInformation_PR_present
} uE_SecurityInformation_PR;
typedef enum ue_CapabilityContainer_PR {
	ue_CapabilityContainer_PR_NOTHING,	/* No components present */
	ue_CapabilityContainer_PR_absent,
	ue_CapabilityContainer_PR_present
} ue_CapabilityContainer_PR;
typedef enum v390NonCriticalExtensions_PR {
	v390NonCriticalExtensions_PR_NOTHING,	/* No components present */
	v390NonCriticalExtensions_PR_absent,
	v390NonCriticalExtensions_PR_present
} v390NonCriticalExtensions_PR;

/* InterRATHandoverInfo */
typedef struct InterRATHandoverInfo {
	struct predefinedConfigStatusList {
		predefinedConfigStatusList_PR present;
		union InterRATHandoverInfo__predefinedConfigStatusList_u {
			NULL_t	 absent;
			PredefinedConfigStatusList_t	 present;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} predefinedConfigStatusList;
	struct uE_SecurityInformation {
		uE_SecurityInformation_PR present;
		union InterRATHandoverInfo__uE_SecurityInformation_u {
			NULL_t	 absent;
			UE_SecurityInformation_t	 present;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} uE_SecurityInformation;
	struct ue_CapabilityContainer {
		ue_CapabilityContainer_PR present;
		union InterRATHandoverInfo__ue_CapabilityContainer_u {
			NULL_t	 absent;
			OCTET_STRING_t	 present;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ue_CapabilityContainer;
	struct v390NonCriticalExtensions {
		v390NonCriticalExtensions_PR present;
		union InterRATHandoverInfo__v390NonCriticalExtensions_u {
			NULL_t	 absent;
			struct present {
				InterRATHandoverInfo_v390ext_IEs_t	 interRATHandoverInfo_v390ext;
				struct v3a0NonCriticalExtensions {
					InterRATHandoverInfo_v3a0ext_IEs_t	 interRATHandoverInfo_v3a0ext;
					struct laterNonCriticalExtensions {
						InterRATHandoverInfo_v3d0ext_IEs_t	 interRATHandoverInfo_v3d0ext;
						BIT_STRING_t	*interRATHandoverInfo_r3_add_ext	/* OPTIONAL */;
						struct v3g0NonCriticalExtensions {
							InterRATHandoverInfo_v3g0ext_IEs_t	 interRATHandoverInfo_v3g0ext;
							struct v4b0NonCriticalExtensions {
								InterRATHandoverInfo_v4b0ext_IEs_t	 interRATHandoverInfo_v4b0ext;
								struct v4d0NonCriticalExtensions {
									InterRATHandoverInfo_v4d0ext_IEs_t	 interRATHandoverInfo_v4d0ext;
									struct v590NonCriticalExtensions {
										InterRATHandoverInfo_v590ext_IEs_t	 interRATHandoverInfo_v590ext;
										struct v690NonCriticalExtensions {
											InterRATHandoverInfo_v690ext_IEs_t	 interRATHandoverInfo_v690ext;
											struct v7xyNonCriticalExtensions {
												InterRATHandoverInfo_v7xyext_IEs_t	 interRATHandoverInfo_v7xyext;
												struct nonCriticalExtensions {
													
													/* Context for parsing across buffer boundaries */
													asn_struct_ctx_t _asn_ctx;
												} *nonCriticalExtensions;
												
												/* Context for parsing across buffer boundaries */
												asn_struct_ctx_t _asn_ctx;
											} *v7xyNonCriticalExtensions;
											
											/* Context for parsing across buffer boundaries */
											asn_struct_ctx_t _asn_ctx;
										} *v690NonCriticalExtensions;
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *v590NonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v4d0NonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v4b0NonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v3g0NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *laterNonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *v3a0NonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} present;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} v390NonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterRATHandoverInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRATHandoverInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _InterRATHandoverInfo_H_ */
#include <asn_internal.h>
