/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_Neighbour_v390ext_H_
#define	_Neighbour_v390ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "FrequencyInfo.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum modeSpecificInfo_PR {
	modeSpecificInfo_PR_NOTHING,	/* No components present */
	modeSpecificInfo_PR_fdd,
	modeSpecificInfo_PR_tdd
} modeSpecificInfo_PR;

/* Neighbour-v390ext */
typedef struct Neighbour_v390ext {
	struct modeSpecificInfo {
		modeSpecificInfo_PR present;
		union Neighbour_v390ext__modeSpecificInfo_u {
			struct fdd {
				FrequencyInfo_t	 frequencyInfo;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			NULL_t	 tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Neighbour_v390ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Neighbour_v390ext;

#ifdef __cplusplus
}
#endif

#endif	/* _Neighbour_v390ext_H_ */
#include <asn_internal.h>
