/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_PUSCH_PowerControlInfo_r7_H_
#define	_PUSCH_PowerControlInfo_r7_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UL-TargetSIR.h"
#include <NULL.h>
#include "TPC-StepSizeTDD.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum tddOption_PR {
	tddOption_PR_NOTHING,	/* No components present */
	tddOption_PR_tdd384,
	tddOption_PR_tdd768,
	tddOption_PR_tdd128
} tddOption_PR;

/* PUSCH-PowerControlInfo-r7 */
typedef struct PUSCH_PowerControlInfo_r7 {
	UL_TargetSIR_t	 ul_TargetSIR;
	struct tddOption {
		tddOption_PR present;
		union PUSCH_PowerControlInfo_r7__tddOption_u {
			NULL_t	 tdd384;
			NULL_t	 tdd768;
			struct tdd128 {
				TPC_StepSizeTDD_t	*tpc_StepSize	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd128;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tddOption;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PUSCH_PowerControlInfo_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PUSCH_PowerControlInfo_r7;

#ifdef __cplusplus
}
#endif

#endif	/* _PUSCH_PowerControlInfo_r7_H_ */
#include <asn_internal.h>
