/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_Q_RxlevMin_H_
#define	_Q_RxlevMin_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Q-RxlevMin */
typedef long	 Q_RxlevMin_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Q_RxlevMin;
asn_struct_free_f Q_RxlevMin_free;
asn_struct_print_f Q_RxlevMin_print;
asn_constr_check_f Q_RxlevMin_constraint;
ber_type_decoder_f Q_RxlevMin_decode_ber;
der_type_encoder_f Q_RxlevMin_encode_der;
xer_type_decoder_f Q_RxlevMin_decode_xer;
xer_type_encoder_f Q_RxlevMin_encode_xer;
per_type_decoder_f Q_RxlevMin_decode_uper;
per_type_encoder_f Q_RxlevMin_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Q_RxlevMin_H_ */
#include <asn_internal.h>
