/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrc.asn1"
 */

#ifndef	_RRCConnectionRelease_H_
#define	_RRCConnectionRelease_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RRCConnectionRelease-r3-IEs.h"
#include <BIT_STRING.h>
#include "RRCConnectionRelease-v690ext-IEs.h"
#include <constr_SEQUENCE.h>
#include "RRC-TransactionIdentifier.h"
#include "RRCConnectionRelease-r4-IEs.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionRelease_PR {
	RRCConnectionRelease_PR_NOTHING,	/* No components present */
	RRCConnectionRelease_PR_r3,
	RRCConnectionRelease_PR_later_than_r3
} RRCConnectionRelease_PR;
typedef enum criticalExtensions_PR {
	criticalExtensions_PR_NOTHING,	/* No components present */
	criticalExtensions_PR_r4,
	criticalExtensions_PR_criticalExtensions
} criticalExtensions_PR;

/* RRCConnectionRelease */
typedef struct RRCConnectionRelease {
	RRCConnectionRelease_PR present;
	union RRCConnectionRelease_u {
		struct r3 {
			RRCConnectionRelease_r3_IEs_t	 rrcConnectionRelease_r3;
			struct laterNonCriticalExtensions {
				BIT_STRING_t	*rrcConnectionRelease_r3_add_ext	/* OPTIONAL */;
				struct v690NonCriticalExtensions {
					RRCConnectionRelease_v690ext_IEs_t	 rrcConnectionRelease_v690ext;
					struct nonCriticalExtensions {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *nonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *v690NonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *laterNonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct later_than_r3 {
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct criticalExtensions {
				criticalExtensions_PR present;
				union RRCConnectionRelease__later_than_r3__criticalExtensions_u {
					struct r4 {
						RRCConnectionRelease_r4_IEs_t	 rrcConnectionRelease_r4;
						struct v4d0NonCriticalExtensions {
							BIT_STRING_t	*rrcConnectionRelease_r4_add_ext	/* OPTIONAL */;
							struct v690NonCriticalExtensions {
								RRCConnectionRelease_v690ext_IEs_t	 rrcConnectionRelease_v690ext;
								struct nonCriticalExtensions {
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *nonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v690NonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v4d0NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} r4;
					struct criticalExtensions {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} criticalExtensions;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRelease_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionRelease_H_ */
#include <asn_internal.h>
