/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rrc.asn1"
 */

#include "RRCConnectionSetup.h"

static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_46 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_39 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_30 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_criticalExtensions_constr_18 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_RRCConnectionSetup_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_14 = {
	sizeof(struct nonCriticalExtensions),
	offsetof(struct nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_14 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_14,
	sizeof(asn_DEF_nonCriticalExtensions_tags_14)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_14[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_14,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_14)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v7xyNonCriticalExtensions_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v7xyNonCriticalExtensions, rrcConnectionSetup_v7xyext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v7xyext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v7xyext"
		},
	{ ATF_POINTER, 1, offsetof(struct v7xyNonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v7xyNonCriticalExtensions_oms_12[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v7xyNonCriticalExtensions_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v7xyNonCriticalExtensions_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v7xyext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v7xyNonCriticalExtensions_specs_12 = {
	sizeof(struct v7xyNonCriticalExtensions),
	offsetof(struct v7xyNonCriticalExtensions, _asn_ctx),
	asn_MAP_v7xyNonCriticalExtensions_tag2el_12,
	2,	/* Count of tags in the map */
	asn_MAP_v7xyNonCriticalExtensions_oms_12,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v7xyNonCriticalExtensions_12 = {
	"v7xyNonCriticalExtensions",
	"v7xyNonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v7xyNonCriticalExtensions_tags_12,
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_12[0]) - 1, /* 1 */
	asn_DEF_v7xyNonCriticalExtensions_tags_12,	/* Same as above */
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v7xyNonCriticalExtensions_12,
	2,	/* Elements count */
	&asn_SPC_v7xyNonCriticalExtensions_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v690NonCriticalExtensions, rrcConnectionSetup_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v690ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v690NonCriticalExtensions, v7xyNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v7xyNonCriticalExtensions_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v7xyNonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_10[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v7xyNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_10 = {
	sizeof(struct v690NonCriticalExtensions),
	offsetof(struct v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_10,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_10 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v690NonCriticalExtensions_tags_10,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_10[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v690NonCriticalExtensions_10,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v590NonCriticalExtensions_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v590NonCriticalExtensions, rrcConnectionSetup_v590ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v590ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v590ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v590NonCriticalExtensions, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_v590NonCriticalExtensions_oms_8[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v590NonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v590NonCriticalExtensions_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v590ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v590NonCriticalExtensions_specs_8 = {
	sizeof(struct v590NonCriticalExtensions),
	offsetof(struct v590NonCriticalExtensions, _asn_ctx),
	asn_MAP_v590NonCriticalExtensions_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_v590NonCriticalExtensions_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v590NonCriticalExtensions_8 = {
	"v590NonCriticalExtensions",
	"v590NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v590NonCriticalExtensions_tags_8,
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_v590NonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v590NonCriticalExtensions_8,
	2,	/* Elements count */
	&asn_SPC_v590NonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v4b0NonCriticalExtensions_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v4b0NonCriticalExtensions, rrcConnectionSetup_v4b0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v4b0ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v4b0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v4b0NonCriticalExtensions, v590NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v590NonCriticalExtensions_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v590NonCriticalExtensions"
		},
};
static const int asn_MAP_v4b0NonCriticalExtensions_oms_6[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v4b0NonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v4b0NonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v4b0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v590NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v4b0NonCriticalExtensions_specs_6 = {
	sizeof(struct v4b0NonCriticalExtensions),
	offsetof(struct v4b0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v4b0NonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_v4b0NonCriticalExtensions_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v4b0NonCriticalExtensions_6 = {
	"v4b0NonCriticalExtensions",
	"v4b0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v4b0NonCriticalExtensions_tags_6,
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_v4b0NonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v4b0NonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_v4b0NonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_laterNonCriticalExtensions_4[] = {
	{ ATF_POINTER, 2, offsetof(struct laterNonCriticalExtensions, rrcConnectionSetup_r3_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r3-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct laterNonCriticalExtensions, v4b0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v4b0NonCriticalExtensions_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v4b0NonCriticalExtensions"
		},
};
static const int asn_MAP_laterNonCriticalExtensions_oms_4[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_laterNonCriticalExtensions_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_laterNonCriticalExtensions_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-r3-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v4b0NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_laterNonCriticalExtensions_specs_4 = {
	sizeof(struct laterNonCriticalExtensions),
	offsetof(struct laterNonCriticalExtensions, _asn_ctx),
	asn_MAP_laterNonCriticalExtensions_tag2el_4,
	2,	/* Count of tags in the map */
	asn_MAP_laterNonCriticalExtensions_oms_4,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_laterNonCriticalExtensions_4 = {
	"laterNonCriticalExtensions",
	"laterNonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_laterNonCriticalExtensions_tags_4,
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_4[0]) - 1, /* 1 */
	asn_DEF_laterNonCriticalExtensions_tags_4,	/* Same as above */
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_4)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_laterNonCriticalExtensions_4,
	2,	/* Elements count */
	&asn_SPC_laterNonCriticalExtensions_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r3_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct r3, rrcConnectionSetup_r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_r3_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r3"
		},
	{ ATF_POINTER, 1, offsetof(struct r3, laterNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_laterNonCriticalExtensions_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"laterNonCriticalExtensions"
		},
};
static const int asn_MAP_r3_oms_2[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r3_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r3_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* laterNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r3_specs_2 = {
	sizeof(struct r3),
	offsetof(struct r3, _asn_ctx),
	asn_MAP_r3_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_r3_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r3_2 = {
	"r3",
	"r3",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_r3_tags_2,
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]) - 1, /* 1 */
	asn_DEF_r3_tags_2,	/* Same as above */
	sizeof(asn_DEF_r3_tags_2)
		/sizeof(asn_DEF_r3_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_r3_2,
	2,	/* Elements count */
	&asn_SPC_r3_specs_2	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_29[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_29 = {
	sizeof(struct nonCriticalExtensions),
	offsetof(struct nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_29 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_29,
	sizeof(asn_DEF_nonCriticalExtensions_tags_29)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_29[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_29,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_29)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_29[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_29	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v7xyNonCriticalExtensions_27[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v7xyNonCriticalExtensions, rrcConnectionSetup_v7xyext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v7xyext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v7xyext"
		},
	{ ATF_POINTER, 1, offsetof(struct v7xyNonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_29,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v7xyNonCriticalExtensions_oms_27[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v7xyNonCriticalExtensions_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v7xyNonCriticalExtensions_tag2el_27[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v7xyext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v7xyNonCriticalExtensions_specs_27 = {
	sizeof(struct v7xyNonCriticalExtensions),
	offsetof(struct v7xyNonCriticalExtensions, _asn_ctx),
	asn_MAP_v7xyNonCriticalExtensions_tag2el_27,
	2,	/* Count of tags in the map */
	asn_MAP_v7xyNonCriticalExtensions_oms_27,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v7xyNonCriticalExtensions_27 = {
	"v7xyNonCriticalExtensions",
	"v7xyNonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v7xyNonCriticalExtensions_tags_27,
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_27)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_27[0]) - 1, /* 1 */
	asn_DEF_v7xyNonCriticalExtensions_tags_27,	/* Same as above */
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_27)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_27[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v7xyNonCriticalExtensions_27,
	2,	/* Elements count */
	&asn_SPC_v7xyNonCriticalExtensions_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_25[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v690NonCriticalExtensions, rrcConnectionSetup_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v690ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v690NonCriticalExtensions, v7xyNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v7xyNonCriticalExtensions_27,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v7xyNonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_25[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_25[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_25[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v7xyNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_25 = {
	sizeof(struct v690NonCriticalExtensions),
	offsetof(struct v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_25,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_25,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_25 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v690NonCriticalExtensions_tags_25,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_25)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_25[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_25,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_25)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_25[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v690NonCriticalExtensions_25,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_25	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v590NonCriticalExtensions_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v590NonCriticalExtensions, rrcConnectionSetup_v590ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v590ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v590ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v590NonCriticalExtensions, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_25,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_v590NonCriticalExtensions_oms_23[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v590NonCriticalExtensions_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v590NonCriticalExtensions_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v590ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v590NonCriticalExtensions_specs_23 = {
	sizeof(struct v590NonCriticalExtensions),
	offsetof(struct v590NonCriticalExtensions, _asn_ctx),
	asn_MAP_v590NonCriticalExtensions_tag2el_23,
	2,	/* Count of tags in the map */
	asn_MAP_v590NonCriticalExtensions_oms_23,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v590NonCriticalExtensions_23 = {
	"v590NonCriticalExtensions",
	"v590NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v590NonCriticalExtensions_tags_23,
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_23)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_23[0]) - 1, /* 1 */
	asn_DEF_v590NonCriticalExtensions_tags_23,	/* Same as above */
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_23)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_23[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v590NonCriticalExtensions_23,
	2,	/* Elements count */
	&asn_SPC_v590NonCriticalExtensions_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v4d0NonCriticalExtensions_21[] = {
	{ ATF_POINTER, 2, offsetof(struct v4d0NonCriticalExtensions, rrcConnectionSetup_r4_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r4-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v4d0NonCriticalExtensions, v590NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v590NonCriticalExtensions_23,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v590NonCriticalExtensions"
		},
};
static const int asn_MAP_v4d0NonCriticalExtensions_oms_21[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_v4d0NonCriticalExtensions_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v4d0NonCriticalExtensions_tag2el_21[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-r4-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v590NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v4d0NonCriticalExtensions_specs_21 = {
	sizeof(struct v4d0NonCriticalExtensions),
	offsetof(struct v4d0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v4d0NonCriticalExtensions_tag2el_21,
	2,	/* Count of tags in the map */
	asn_MAP_v4d0NonCriticalExtensions_oms_21,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v4d0NonCriticalExtensions_21 = {
	"v4d0NonCriticalExtensions",
	"v4d0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v4d0NonCriticalExtensions_tags_21,
	sizeof(asn_DEF_v4d0NonCriticalExtensions_tags_21)
		/sizeof(asn_DEF_v4d0NonCriticalExtensions_tags_21[0]) - 1, /* 1 */
	asn_DEF_v4d0NonCriticalExtensions_tags_21,	/* Same as above */
	sizeof(asn_DEF_v4d0NonCriticalExtensions_tags_21)
		/sizeof(asn_DEF_v4d0NonCriticalExtensions_tags_21[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v4d0NonCriticalExtensions_21,
	2,	/* Elements count */
	&asn_SPC_v4d0NonCriticalExtensions_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r4_19[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct r4, rrcConnectionSetup_r4),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_r4_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r4"
		},
	{ ATF_POINTER, 1, offsetof(struct r4, v4d0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v4d0NonCriticalExtensions_21,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v4d0NonCriticalExtensions"
		},
};
static const int asn_MAP_r4_oms_19[] = { 1 };
static const ber_tlv_tag_t asn_DEF_r4_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r4_tag2el_19[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-r4 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v4d0NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r4_specs_19 = {
	sizeof(struct r4),
	offsetof(struct r4, _asn_ctx),
	asn_MAP_r4_tag2el_19,
	2,	/* Count of tags in the map */
	asn_MAP_r4_oms_19,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r4_19 = {
	"r4",
	"r4",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_r4_tags_19,
	sizeof(asn_DEF_r4_tags_19)
		/sizeof(asn_DEF_r4_tags_19[0]) - 1, /* 1 */
	asn_DEF_r4_tags_19,	/* Same as above */
	sizeof(asn_DEF_r4_tags_19)
		/sizeof(asn_DEF_r4_tags_19[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_r4_19,
	2,	/* Elements count */
	&asn_SPC_r4_specs_19	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_38[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_38 = {
	sizeof(struct nonCriticalExtensions),
	offsetof(struct nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_38 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_38,
	sizeof(asn_DEF_nonCriticalExtensions_tags_38)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_38[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_38,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_38)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_38[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_38	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v7xyNonCriticalExtensions_36[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v7xyNonCriticalExtensions, rrcConnectionSetup_v7xyext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v7xyext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v7xyext"
		},
	{ ATF_POINTER, 1, offsetof(struct v7xyNonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_38,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v7xyNonCriticalExtensions_oms_36[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v7xyNonCriticalExtensions_tags_36[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v7xyNonCriticalExtensions_tag2el_36[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v7xyext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v7xyNonCriticalExtensions_specs_36 = {
	sizeof(struct v7xyNonCriticalExtensions),
	offsetof(struct v7xyNonCriticalExtensions, _asn_ctx),
	asn_MAP_v7xyNonCriticalExtensions_tag2el_36,
	2,	/* Count of tags in the map */
	asn_MAP_v7xyNonCriticalExtensions_oms_36,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v7xyNonCriticalExtensions_36 = {
	"v7xyNonCriticalExtensions",
	"v7xyNonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v7xyNonCriticalExtensions_tags_36,
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_36)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_36[0]) - 1, /* 1 */
	asn_DEF_v7xyNonCriticalExtensions_tags_36,	/* Same as above */
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_36)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_36[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v7xyNonCriticalExtensions_36,
	2,	/* Elements count */
	&asn_SPC_v7xyNonCriticalExtensions_specs_36	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_34[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v690NonCriticalExtensions, rrcConnectionSetup_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v690ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v690NonCriticalExtensions, v7xyNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v7xyNonCriticalExtensions_36,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v7xyNonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_34[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_34[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_34[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v7xyNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_34 = {
	sizeof(struct v690NonCriticalExtensions),
	offsetof(struct v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_34,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_34,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_34 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v690NonCriticalExtensions_tags_34,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_34)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_34[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_34,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_34)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_34[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v690NonCriticalExtensions_34,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_34	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r5_31[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct r5, rrcConnectionSetup_r5),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_r5_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r5"
		},
	{ ATF_POINTER, 2, offsetof(struct r5, rrcConnectionSetup_r5_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r5-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct r5, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_34,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_r5_oms_31[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_r5_tags_31[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r5_tag2el_31[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-r5 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rrcConnectionSetup-r5-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r5_specs_31 = {
	sizeof(struct r5),
	offsetof(struct r5, _asn_ctx),
	asn_MAP_r5_tag2el_31,
	3,	/* Count of tags in the map */
	asn_MAP_r5_oms_31,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r5_31 = {
	"r5",
	"r5",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_r5_tags_31,
	sizeof(asn_DEF_r5_tags_31)
		/sizeof(asn_DEF_r5_tags_31[0]) - 1, /* 1 */
	asn_DEF_r5_tags_31,	/* Same as above */
	sizeof(asn_DEF_r5_tags_31)
		/sizeof(asn_DEF_r5_tags_31[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_r5_31,
	3,	/* Elements count */
	&asn_SPC_r5_specs_31	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_45[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_45 = {
	sizeof(struct nonCriticalExtensions),
	offsetof(struct nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_45 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_45,
	sizeof(asn_DEF_nonCriticalExtensions_tags_45)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_45[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_45,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_45)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_45[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_45	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v7xyNonCriticalExtensions_43[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v7xyNonCriticalExtensions, rrcConnectionSetup_v7xyext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_v7xyext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-v7xyext"
		},
	{ ATF_POINTER, 1, offsetof(struct v7xyNonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_45,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v7xyNonCriticalExtensions_oms_43[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v7xyNonCriticalExtensions_tags_43[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v7xyNonCriticalExtensions_tag2el_43[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-v7xyext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v7xyNonCriticalExtensions_specs_43 = {
	sizeof(struct v7xyNonCriticalExtensions),
	offsetof(struct v7xyNonCriticalExtensions, _asn_ctx),
	asn_MAP_v7xyNonCriticalExtensions_tag2el_43,
	2,	/* Count of tags in the map */
	asn_MAP_v7xyNonCriticalExtensions_oms_43,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v7xyNonCriticalExtensions_43 = {
	"v7xyNonCriticalExtensions",
	"v7xyNonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v7xyNonCriticalExtensions_tags_43,
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_43)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_43[0]) - 1, /* 1 */
	asn_DEF_v7xyNonCriticalExtensions_tags_43,	/* Same as above */
	sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_43)
		/sizeof(asn_DEF_v7xyNonCriticalExtensions_tags_43[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v7xyNonCriticalExtensions_43,
	2,	/* Elements count */
	&asn_SPC_v7xyNonCriticalExtensions_specs_43	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r6_40[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct r6, rrcConnectionSetup_r6),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_r6_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r6"
		},
	{ ATF_POINTER, 2, offsetof(struct r6, rrcConnectionSetup_r6_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r6-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct r6, v7xyNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_v7xyNonCriticalExtensions_43,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v7xyNonCriticalExtensions"
		},
};
static const int asn_MAP_r6_oms_40[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_r6_tags_40[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r6_tag2el_40[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-r6 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rrcConnectionSetup-r6-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* v7xyNonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r6_specs_40 = {
	sizeof(struct r6),
	offsetof(struct r6, _asn_ctx),
	asn_MAP_r6_tag2el_40,
	3,	/* Count of tags in the map */
	asn_MAP_r6_oms_40,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r6_40 = {
	"r6",
	"r6",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_r6_tags_40,
	sizeof(asn_DEF_r6_tags_40)
		/sizeof(asn_DEF_r6_tags_40[0]) - 1, /* 1 */
	asn_DEF_r6_tags_40,	/* Same as above */
	sizeof(asn_DEF_r6_tags_40)
		/sizeof(asn_DEF_r6_tags_40[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_r6_40,
	3,	/* Elements count */
	&asn_SPC_r6_specs_40	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_50[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_50 = {
	sizeof(struct nonCriticalExtensions),
	offsetof(struct nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_50 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_50,
	sizeof(asn_DEF_nonCriticalExtensions_tags_50)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_50[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_50,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_50)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_50[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_50	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_r7_47[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct r7, rrcConnectionSetup_r7),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetup_r7_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r7"
		},
	{ ATF_POINTER, 2, offsetof(struct r7, rrcConnectionSetup_r7_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetup-r7-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct r7, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_50,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_r7_oms_47[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_r7_tags_47[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_r7_tag2el_47[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetup-r7 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rrcConnectionSetup-r7-add-ext */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_r7_specs_47 = {
	sizeof(struct r7),
	offsetof(struct r7, _asn_ctx),
	asn_MAP_r7_tag2el_47,
	3,	/* Count of tags in the map */
	asn_MAP_r7_oms_47,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_r7_47 = {
	"r7",
	"r7",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_r7_tags_47,
	sizeof(asn_DEF_r7_tags_47)
		/sizeof(asn_DEF_r7_tags_47[0]) - 1, /* 1 */
	asn_DEF_r7_tags_47,	/* Same as above */
	sizeof(asn_DEF_r7_tags_47)
		/sizeof(asn_DEF_r7_tags_47[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_r7_47,
	3,	/* Elements count */
	&asn_SPC_r7_specs_47	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_criticalExtensions_tags_51[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_criticalExtensions_specs_51 = {
	sizeof(struct criticalExtensions),
	offsetof(struct criticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_51 = {
	"criticalExtensions",
	"criticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_criticalExtensions_tags_51,
	sizeof(asn_DEF_criticalExtensions_tags_51)
		/sizeof(asn_DEF_criticalExtensions_tags_51[0]) - 1, /* 1 */
	asn_DEF_criticalExtensions_tags_51,	/* Same as above */
	sizeof(asn_DEF_criticalExtensions_tags_51)
		/sizeof(asn_DEF_criticalExtensions_tags_51[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_criticalExtensions_specs_51	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_46[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct criticalExtensions, choice.r7),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r7_47,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"r7"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_criticalExtensions_51,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_46[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r7 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_46 = {
	sizeof(struct criticalExtensions),
	offsetof(struct criticalExtensions, _asn_ctx),
	offsetof(struct criticalExtensions, present),
	sizeof(((struct criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_46,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_46 = {
	"criticalExtensions",
	"criticalExtensions",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_criticalExtensions_constr_46,
	asn_MBR_criticalExtensions_46,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_46	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_39[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct criticalExtensions, choice.r6),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r6_40,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"r6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_46,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_39[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r6 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_39 = {
	sizeof(struct criticalExtensions),
	offsetof(struct criticalExtensions, _asn_ctx),
	offsetof(struct criticalExtensions, present),
	sizeof(((struct criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_39,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_39 = {
	"criticalExtensions",
	"criticalExtensions",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_criticalExtensions_constr_39,
	asn_MBR_criticalExtensions_39,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_39	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_30[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct criticalExtensions, choice.r5),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r5_31,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"r5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_39,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_30[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r5 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_30 = {
	sizeof(struct criticalExtensions),
	offsetof(struct criticalExtensions, _asn_ctx),
	offsetof(struct criticalExtensions, present),
	sizeof(((struct criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_30,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_30 = {
	"criticalExtensions",
	"criticalExtensions",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_criticalExtensions_constr_30,
	asn_MBR_criticalExtensions_30,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_30	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_criticalExtensions_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct criticalExtensions, choice.r4),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r4_19,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"r4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct criticalExtensions, choice.criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_30,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"criticalExtensions"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_criticalExtensions_tag2el_18[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r4 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* criticalExtensions */
};
static asn_CHOICE_specifics_t asn_SPC_criticalExtensions_specs_18 = {
	sizeof(struct criticalExtensions),
	offsetof(struct criticalExtensions, _asn_ctx),
	offsetof(struct criticalExtensions, present),
	sizeof(((struct criticalExtensions *)0)->present),
	asn_MAP_criticalExtensions_tag2el_18,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_criticalExtensions_18 = {
	"criticalExtensions",
	"criticalExtensions",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_criticalExtensions_constr_18,
	asn_MBR_criticalExtensions_18,
	2,	/* Elements count */
	&asn_SPC_criticalExtensions_specs_18	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_later_than_r3_15[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct later_than_r3, initialUE_Identity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_InitialUE_Identity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initialUE-Identity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct later_than_r3, rrc_TransactionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_TransactionIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrc-TransactionIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct later_than_r3, criticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_criticalExtensions_18,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"criticalExtensions"
		},
};
static const ber_tlv_tag_t asn_DEF_later_than_r3_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_later_than_r3_tag2el_15[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* initialUE-Identity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rrc-TransactionIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* criticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_later_than_r3_specs_15 = {
	sizeof(struct later_than_r3),
	offsetof(struct later_than_r3, _asn_ctx),
	asn_MAP_later_than_r3_tag2el_15,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_later_than_r3_15 = {
	"later-than-r3",
	"later-than-r3",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_later_than_r3_tags_15,
	sizeof(asn_DEF_later_than_r3_tags_15)
		/sizeof(asn_DEF_later_than_r3_tags_15[0]) - 1, /* 1 */
	asn_DEF_later_than_r3_tags_15,	/* Same as above */
	sizeof(asn_DEF_later_than_r3_tags_15)
		/sizeof(asn_DEF_later_than_r3_tags_15[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_later_than_r3_15,
	3,	/* Elements count */
	&asn_SPC_later_than_r3_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RRCConnectionSetup_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetup, choice.r3),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_r3_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"r3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetup, choice.later_than_r3),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_later_than_r3_15,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"later-than-r3"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_RRCConnectionSetup_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* r3 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* later-than-r3 */
};
static asn_CHOICE_specifics_t asn_SPC_RRCConnectionSetup_specs_1 = {
	sizeof(struct RRCConnectionSetup),
	offsetof(struct RRCConnectionSetup, _asn_ctx),
	offsetof(struct RRCConnectionSetup, present),
	sizeof(((struct RRCConnectionSetup *)0)->present),
	asn_MAP_RRCConnectionSetup_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RRCConnectionSetup = {
	"RRCConnectionSetup",
	"RRCConnectionSetup",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_RRCConnectionSetup_constr_1,
	asn_MBR_RRCConnectionSetup_1,
	2,	/* Elements count */
	&asn_SPC_RRCConnectionSetup_specs_1	/* Additional specs */
};

