/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_SCCPCH_InfoForFACH_r4_H_
#define	_SCCPCH_InfoForFACH_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecondaryCCPCH-Info-r4.h"
#include "TFCS.h"
#include "FACH-PCH-InformationList.h"
#include <NULL.h>
#include "SIB-ReferenceListFACH.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum modeSpecificInfo_PR {
	modeSpecificInfo_PR_NOTHING,	/* No components present */
	modeSpecificInfo_PR_fdd,
	modeSpecificInfo_PR_tdd
} modeSpecificInfo_PR;

/* SCCPCH-InfoForFACH-r4 */
typedef struct SCCPCH_InfoForFACH_r4 {
	SecondaryCCPCH_Info_r4_t	 secondaryCCPCH_Info;
	TFCS_t	 tfcs;
	FACH_PCH_InformationList_t	 fach_PCH_InformationList;
	struct modeSpecificInfo {
		modeSpecificInfo_PR present;
		union SCCPCH_InfoForFACH_r4__modeSpecificInfo_u {
			struct fdd {
				SIB_ReferenceListFACH_t	 sib_ReferenceListFACH;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			NULL_t	 tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCCPCH_InfoForFACH_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCCPCH_InfoForFACH_r4;

#ifdef __cplusplus
}
#endif

#endif	/* _SCCPCH_InfoForFACH_r4_H_ */
#include <asn_internal.h>
