/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_SYNC_UL_Info_r4_H_
#define	_SYNC_UL_Info_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum sync_UL_Codes_Bitmap {
	sync_UL_Codes_Bitmap_code7	= 0,
	sync_UL_Codes_Bitmap_code6	= 1,
	sync_UL_Codes_Bitmap_code5	= 2,
	sync_UL_Codes_Bitmap_code4	= 3,
	sync_UL_Codes_Bitmap_code3	= 4,
	sync_UL_Codes_Bitmap_code2	= 5,
	sync_UL_Codes_Bitmap_code1	= 6,
	sync_UL_Codes_Bitmap_code0	= 7
} e_sync_UL_Codes_Bitmap;
typedef enum max_SYNC_UL_Transmissions {
	max_SYNC_UL_Transmissions_tr1	= 0,
	max_SYNC_UL_Transmissions_tr2	= 1,
	max_SYNC_UL_Transmissions_tr4	= 2,
	max_SYNC_UL_Transmissions_tr8	= 3
} e_max_SYNC_UL_Transmissions;

/* SYNC-UL-Info-r4 */
typedef struct SYNC_UL_Info_r4 {
	BIT_STRING_t	 sync_UL_Codes_Bitmap;
	long	 prxUpPCHdes;
	long	 powerRampStep;
	long	 max_SYNC_UL_Transmissions;
	long	 mmax;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SYNC_UL_Info_r4_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_max_SYNC_UL_Transmissions_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SYNC_UL_Info_r4;

#ifdef __cplusplus
}
#endif

#endif	/* _SYNC_UL_Info_r4_H_ */
#include <asn_internal.h>
