/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#include "SysInfoType11.h"

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_11 = {
	sizeof(struct nonCriticalExtensions),
	offsetof(struct nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_11 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_11,
	sizeof(asn_DEF_nonCriticalExtensions_tags_11)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_11[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_11,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_11)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_11[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v690NonCriticalExtensions, sysInfoType11_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType11_v690ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sysInfoType11-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v690NonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v690NonCriticalExtensions_oms_9[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType11-v690ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_9 = {
	sizeof(struct v690NonCriticalExtensions),
	offsetof(struct v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_9,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_9,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_9 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v690NonCriticalExtensions_tags_9,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_9)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_9[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_9,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_9)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v690NonCriticalExtensions_9,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v590NonCriticalExtension_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v590NonCriticalExtension, sysInfoType11_v590ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType11_v590ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sysInfoType11-v590ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v590NonCriticalExtension, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v690NonCriticalExtensions"
		},
};
static const int asn_MAP_v590NonCriticalExtension_oms_7[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v590NonCriticalExtension_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v590NonCriticalExtension_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType11-v590ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v590NonCriticalExtension_specs_7 = {
	sizeof(struct v590NonCriticalExtension),
	offsetof(struct v590NonCriticalExtension, _asn_ctx),
	asn_MAP_v590NonCriticalExtension_tag2el_7,
	2,	/* Count of tags in the map */
	asn_MAP_v590NonCriticalExtension_oms_7,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v590NonCriticalExtension_7 = {
	"v590NonCriticalExtension",
	"v590NonCriticalExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v590NonCriticalExtension_tags_7,
	sizeof(asn_DEF_v590NonCriticalExtension_tags_7)
		/sizeof(asn_DEF_v590NonCriticalExtension_tags_7[0]) - 1, /* 1 */
	asn_DEF_v590NonCriticalExtension_tags_7,	/* Same as above */
	sizeof(asn_DEF_v590NonCriticalExtension_tags_7)
		/sizeof(asn_DEF_v590NonCriticalExtension_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v590NonCriticalExtension_7,
	2,	/* Elements count */
	&asn_SPC_v590NonCriticalExtension_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v4b0NonCriticalExtensions_5[] = {
	{ ATF_POINTER, 2, offsetof(struct v4b0NonCriticalExtensions, sysInfoType11_v4b0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType11_v4b0ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sysInfoType11-v4b0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v4b0NonCriticalExtensions, v590NonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v590NonCriticalExtension_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v590NonCriticalExtension"
		},
};
static const int asn_MAP_v4b0NonCriticalExtensions_oms_5[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_v4b0NonCriticalExtensions_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v4b0NonCriticalExtensions_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType11-v4b0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v590NonCriticalExtension */
};
static asn_SEQUENCE_specifics_t asn_SPC_v4b0NonCriticalExtensions_specs_5 = {
	sizeof(struct v4b0NonCriticalExtensions),
	offsetof(struct v4b0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v4b0NonCriticalExtensions_tag2el_5,
	2,	/* Count of tags in the map */
	asn_MAP_v4b0NonCriticalExtensions_oms_5,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v4b0NonCriticalExtensions_5 = {
	"v4b0NonCriticalExtensions",
	"v4b0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v4b0NonCriticalExtensions_tags_5,
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_5)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_5[0]) - 1, /* 1 */
	asn_DEF_v4b0NonCriticalExtensions_tags_5,	/* Same as above */
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_5)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v4b0NonCriticalExtensions_5,
	2,	/* Elements count */
	&asn_SPC_v4b0NonCriticalExtensions_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SysInfoType11_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType11, sib12indicator),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib12indicator"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType11, fach_MeasurementOccasionInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FACH_MeasurementOccasionInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fach-MeasurementOccasionInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType11, measurementControlSysInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasurementControlSysInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measurementControlSysInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType11, v4b0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_v4b0NonCriticalExtensions_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v4b0NonCriticalExtensions"
		},
};
static const int asn_MAP_SysInfoType11_oms_1[] = { 1, 3 };
static const ber_tlv_tag_t asn_DEF_SysInfoType11_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SysInfoType11_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sib12indicator */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* fach-MeasurementOccasionInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* measurementControlSysInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* v4b0NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_SysInfoType11_specs_1 = {
	sizeof(struct SysInfoType11),
	offsetof(struct SysInfoType11, _asn_ctx),
	asn_MAP_SysInfoType11_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SysInfoType11_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SysInfoType11 = {
	"SysInfoType11",
	"SysInfoType11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SysInfoType11_tags_1,
	sizeof(asn_DEF_SysInfoType11_tags_1)
		/sizeof(asn_DEF_SysInfoType11_tags_1[0]), /* 1 */
	asn_DEF_SysInfoType11_tags_1,	/* Same as above */
	sizeof(asn_DEF_SysInfoType11_tags_1)
		/sizeof(asn_DEF_SysInfoType11_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SysInfoType11_1,
	4,	/* Elements count */
	&asn_SPC_SysInfoType11_specs_1	/* Additional specs */
};

