/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#include "SysInfoType3.h"

static const ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_14 = {
	sizeof(struct nonCriticalExtensions),
	offsetof(struct nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_14 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_14,
	sizeof(asn_DEF_nonCriticalExtensions_tags_14)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_14[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_14,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_14)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v670NonCriticalExtension_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v670NonCriticalExtension, sysInfoType3_v670ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType3_v670ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sysInfoType3-v670ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v670NonCriticalExtension, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static const int asn_MAP_v670NonCriticalExtension_oms_12[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v670NonCriticalExtension_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v670NonCriticalExtension_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType3-v670ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_v670NonCriticalExtension_specs_12 = {
	sizeof(struct v670NonCriticalExtension),
	offsetof(struct v670NonCriticalExtension, _asn_ctx),
	asn_MAP_v670NonCriticalExtension_tag2el_12,
	2,	/* Count of tags in the map */
	asn_MAP_v670NonCriticalExtension_oms_12,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v670NonCriticalExtension_12 = {
	"v670NonCriticalExtension",
	"v670NonCriticalExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v670NonCriticalExtension_tags_12,
	sizeof(asn_DEF_v670NonCriticalExtension_tags_12)
		/sizeof(asn_DEF_v670NonCriticalExtension_tags_12[0]) - 1, /* 1 */
	asn_DEF_v670NonCriticalExtension_tags_12,	/* Same as above */
	sizeof(asn_DEF_v670NonCriticalExtension_tags_12)
		/sizeof(asn_DEF_v670NonCriticalExtension_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v670NonCriticalExtension_12,
	2,	/* Elements count */
	&asn_SPC_v670NonCriticalExtension_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v5c0NoncriticalExtension_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v5c0NoncriticalExtension, sysInfoType3_v5c0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType3_v5c0ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sysInfoType3-v5c0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v5c0NoncriticalExtension, v670NonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v670NonCriticalExtension_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v670NonCriticalExtension"
		},
};
static const int asn_MAP_v5c0NoncriticalExtension_oms_10[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v5c0NoncriticalExtension_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v5c0NoncriticalExtension_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType3-v5c0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v670NonCriticalExtension */
};
static asn_SEQUENCE_specifics_t asn_SPC_v5c0NoncriticalExtension_specs_10 = {
	sizeof(struct v5c0NoncriticalExtension),
	offsetof(struct v5c0NoncriticalExtension, _asn_ctx),
	asn_MAP_v5c0NoncriticalExtension_tag2el_10,
	2,	/* Count of tags in the map */
	asn_MAP_v5c0NoncriticalExtension_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v5c0NoncriticalExtension_10 = {
	"v5c0NoncriticalExtension",
	"v5c0NoncriticalExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v5c0NoncriticalExtension_tags_10,
	sizeof(asn_DEF_v5c0NoncriticalExtension_tags_10)
		/sizeof(asn_DEF_v5c0NoncriticalExtension_tags_10[0]) - 1, /* 1 */
	asn_DEF_v5c0NoncriticalExtension_tags_10,	/* Same as above */
	sizeof(asn_DEF_v5c0NoncriticalExtension_tags_10)
		/sizeof(asn_DEF_v5c0NoncriticalExtension_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v5c0NoncriticalExtension_10,
	2,	/* Elements count */
	&asn_SPC_v5c0NoncriticalExtension_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v590NonCriticalExtension_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v590NonCriticalExtension, sysInfoType3_v590ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType3_v590ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sysInfoType3-v590ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v590NonCriticalExtension, v5c0NoncriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v5c0NoncriticalExtension_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v5c0NoncriticalExtension"
		},
};
static const int asn_MAP_v590NonCriticalExtension_oms_8[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v590NonCriticalExtension_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v590NonCriticalExtension_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType3-v590ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v5c0NoncriticalExtension */
};
static asn_SEQUENCE_specifics_t asn_SPC_v590NonCriticalExtension_specs_8 = {
	sizeof(struct v590NonCriticalExtension),
	offsetof(struct v590NonCriticalExtension, _asn_ctx),
	asn_MAP_v590NonCriticalExtension_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_v590NonCriticalExtension_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v590NonCriticalExtension_8 = {
	"v590NonCriticalExtension",
	"v590NonCriticalExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v590NonCriticalExtension_tags_8,
	sizeof(asn_DEF_v590NonCriticalExtension_tags_8)
		/sizeof(asn_DEF_v590NonCriticalExtension_tags_8[0]) - 1, /* 1 */
	asn_DEF_v590NonCriticalExtension_tags_8,	/* Same as above */
	sizeof(asn_DEF_v590NonCriticalExtension_tags_8)
		/sizeof(asn_DEF_v590NonCriticalExtension_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v590NonCriticalExtension_8,
	2,	/* Elements count */
	&asn_SPC_v590NonCriticalExtension_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v4b0NonCriticalExtensions_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct v4b0NonCriticalExtensions, sysInfoType3_v4b0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SysInfoType3_v4b0ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sysInfoType3-v4b0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct v4b0NonCriticalExtensions, v590NonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v590NonCriticalExtension_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v590NonCriticalExtension"
		},
};
static const int asn_MAP_v4b0NonCriticalExtensions_oms_6[] = { 1 };
static const ber_tlv_tag_t asn_DEF_v4b0NonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_v4b0NonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sysInfoType3-v4b0ext */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v590NonCriticalExtension */
};
static asn_SEQUENCE_specifics_t asn_SPC_v4b0NonCriticalExtensions_specs_6 = {
	sizeof(struct v4b0NonCriticalExtensions),
	offsetof(struct v4b0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v4b0NonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_v4b0NonCriticalExtensions_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v4b0NonCriticalExtensions_6 = {
	"v4b0NonCriticalExtensions",
	"v4b0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v4b0NonCriticalExtensions_tags_6,
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_v4b0NonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v4b0NonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_v4b0NonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SysInfoType3_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType3, sib4indicator),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sib4indicator"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType3, cellIdentity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cellIdentity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType3, cellSelectReselectInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellSelectReselectInfoSIB_3_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cellSelectReselectInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SysInfoType3, cellAccessRestriction),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellAccessRestriction,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cellAccessRestriction"
		},
	{ ATF_POINTER, 1, offsetof(struct SysInfoType3, v4b0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_v4b0NonCriticalExtensions_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v4b0NonCriticalExtensions"
		},
};
static const int asn_MAP_SysInfoType3_oms_1[] = { 4 };
static const ber_tlv_tag_t asn_DEF_SysInfoType3_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SysInfoType3_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sib4indicator */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cellIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cellSelectReselectInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cellAccessRestriction */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* v4b0NonCriticalExtensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_SysInfoType3_specs_1 = {
	sizeof(struct SysInfoType3),
	offsetof(struct SysInfoType3, _asn_ctx),
	asn_MAP_SysInfoType3_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SysInfoType3_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SysInfoType3 = {
	"SysInfoType3",
	"SysInfoType3",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SysInfoType3_tags_1,
	sizeof(asn_DEF_SysInfoType3_tags_1)
		/sizeof(asn_DEF_SysInfoType3_tags_1[0]), /* 1 */
	asn_DEF_SysInfoType3_tags_1,	/* Same as above */
	sizeof(asn_DEF_SysInfoType3_tags_1)
		/sizeof(asn_DEF_SysInfoType3_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SysInfoType3_1,
	5,	/* Elements count */
	&asn_SPC_SysInfoType3_specs_1	/* Additional specs */
};

