/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_SysInfoTypeSB2_H_
#define	_SysInfoTypeSB2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SIB-ReferenceList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SysInfoTypeSB2 */
typedef struct SysInfoTypeSB2 {
	SIB_ReferenceList_t	 sib_ReferenceList;
	struct nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoTypeSB2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoTypeSB2;

#ifdef __cplusplus
}
#endif

#endif	/* _SysInfoTypeSB2_H_ */
#include <asn_internal.h>
