/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_TFCS_ReconfAdd_H_
#define	_TFCS_ReconfAdd_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ctfcSize_PR {
	ctfcSize_PR_NOTHING,	/* No components present */
	ctfcSize_PR_ctfc2Bit,
	ctfcSize_PR_ctfc4Bit,
	ctfcSize_PR_ctfc6Bit,
	ctfcSize_PR_ctfc8Bit,
	ctfcSize_PR_ctfc12Bit,
	ctfcSize_PR_ctfc16Bit,
	ctfcSize_PR_ctfc24Bit
} ctfcSize_PR;

/* Forward declarations */
struct PowerOffsetInformation;

/* TFCS-ReconfAdd */
typedef struct TFCS_ReconfAdd {
	struct ctfcSize {
		ctfcSize_PR present;
		union TFCS_ReconfAdd__ctfcSize_u {
			struct ctfc2Bit {
				A_SEQUENCE_OF(struct Member {
					long	 ctfc2;
					struct PowerOffsetInformation	*powerOffsetInformation	/* OPTIONAL */;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ctfc2Bit;
			struct ctfc4Bit {
				A_SEQUENCE_OF(struct Member {
					long	 ctfc4;
					struct PowerOffsetInformation	*powerOffsetInformation	/* OPTIONAL */;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ctfc4Bit;
			struct ctfc6Bit {
				A_SEQUENCE_OF(struct Member {
					long	 ctfc6;
					struct PowerOffsetInformation	*powerOffsetInformation	/* OPTIONAL */;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ctfc6Bit;
			struct ctfc8Bit {
				A_SEQUENCE_OF(struct Member {
					long	 ctfc8;
					struct PowerOffsetInformation	*powerOffsetInformation	/* OPTIONAL */;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ctfc8Bit;
			struct ctfc12Bit {
				A_SEQUENCE_OF(struct Member {
					long	 ctfc12;
					struct PowerOffsetInformation	*powerOffsetInformation	/* OPTIONAL */;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ctfc12Bit;
			struct ctfc16Bit {
				A_SEQUENCE_OF(struct Member {
					long	 ctfc16;
					struct PowerOffsetInformation	*powerOffsetInformation	/* OPTIONAL */;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ctfc16Bit;
			struct ctfc24Bit {
				A_SEQUENCE_OF(struct Member {
					long	 ctfc24;
					struct PowerOffsetInformation	*powerOffsetInformation	/* OPTIONAL */;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} ) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ctfc24Bit;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ctfcSize;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TFCS_ReconfAdd_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TFCS_ReconfAdd;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PowerOffsetInformation.h"

#endif	/* _TFCS_ReconfAdd_H_ */
#include <asn_internal.h>
