/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_UE_Positioning_PositionEstimateInfo_H_
#define	_UE_Positioning_PositionEstimateInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionEstimate.h"
#include "UTRAN-GPSReferenceTimeResult.h"
#include <NativeInteger.h>
#include "PrimaryCPICH-Info.h"
#include <constr_SEQUENCE.h>
#include "CellAndChannelIdentity.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum referenceTime_PR {
	referenceTime_PR_NOTHING,	/* No components present */
	referenceTime_PR_utran_GPSReferenceTimeResult,
	referenceTime_PR_gps_ReferenceTimeOnly,
	referenceTime_PR_cell_Timing
} referenceTime_PR;
typedef enum modeSpecificInfo_PR {
	modeSpecificInfo_PR_NOTHING,	/* No components present */
	modeSpecificInfo_PR_fdd,
	modeSpecificInfo_PR_tdd
} modeSpecificInfo_PR;

/* UE-Positioning-PositionEstimateInfo */
typedef struct UE_Positioning_PositionEstimateInfo {
	struct referenceTime {
		referenceTime_PR present;
		union UE_Positioning_PositionEstimateInfo__referenceTime_u {
			UTRAN_GPSReferenceTimeResult_t	 utran_GPSReferenceTimeResult;
			long	 gps_ReferenceTimeOnly;
			struct cell_Timing {
				long	 sfn;
				struct modeSpecificInfo {
					modeSpecificInfo_PR present;
					union UE_Positioning_PositionEstimateInfo__referenceTime__cell_Timing__modeSpecificInfo_u {
						struct fdd {
							PrimaryCPICH_Info_t	 primaryCPICH_Info;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} fdd;
						struct tdd {
							CellAndChannelIdentity_t	 cellAndChannelIdentity;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} tdd;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} modeSpecificInfo;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} cell_Timing;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} referenceTime;
	PositionEstimate_t	 positionEstimate;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_Positioning_PositionEstimateInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Positioning_PositionEstimateInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_Positioning_PositionEstimateInfo_H_ */
#include <asn_internal.h>
