/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rrc.asn1"
 */

#ifndef	_UplinkAdditionalTimeslots_LCR_r4_H_
#define	_UplinkAdditionalTimeslots_LCR_r4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeslotNumber.h"
#include <constr_SEQUENCE.h>
#include "IndividualTimeslotInfo-LCR-r4.h"
#include "UL-TS-ChannelisationCodeList.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum parameters_PR {
	parameters_PR_NOTHING,	/* No components present */
	parameters_PR_sameAsLast,
	parameters_PR_newParameters
} parameters_PR;

/* UplinkAdditionalTimeslots-LCR-r4 */
typedef struct UplinkAdditionalTimeslots_LCR_r4 {
	struct parameters {
		parameters_PR present;
		union UplinkAdditionalTimeslots_LCR_r4__parameters_u {
			struct sameAsLast {
				TimeslotNumber_t	 timeslotNumber;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} sameAsLast;
			struct newParameters {
				IndividualTimeslotInfo_LCR_r4_t	 individualTimeslotInfo;
				UL_TS_ChannelisationCodeList_t	 ul_TS_ChannelisationCodeList;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} newParameters;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} parameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UplinkAdditionalTimeslots_LCR_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UplinkAdditionalTimeslots_LCR_r4;

#ifdef __cplusplus
}
#endif

#endif	/* _UplinkAdditionalTimeslots_LCR_r4_H_ */
#include <asn_internal.h>
